mbtiproj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'rootproj'
urlpatterns = [
    url(r'', include('src.apps.registration.urls'), name = 'registration'),
    url(r'^personalp/', include('src.apps.personalp.urls'), name = 'personalp'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^sociotypetest/', include('src.apps.sociotypetest.urls'), name = 'sociotypetest'),
    #url(r'^registration/', include('src.apps.registration.urls'), name = 'registration'),
    url(r'^authentification/', include('src.apps.authentification.urls'), name = 'authentification'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL)

src/apps/authentification/urls.py
from django.conf.urls import url
from . import views

app_name = 'authentification'
urlpatterns = [
    url(r'^login/$', views.login_for_user, name='login_for_user'),
    url(r'^logout/$', views.logout_for_user, name='logout_for_user'),
]

src/apps/personalp/urls.py
from django.conf.urls import url
from . import views

app_name = 'personalp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<personal_id>[0-9]+)/$', views.personal_info, name = 'personal_info'),
]

src/apps/registration/urls.py
from django.conf.urls import url
from . import views

app_name = 'registration'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^registration/new_account$', views.register, name='register'),
    #url(r'^login/$', 'django.contrib.auth.views.login', { "template_name": "accounts/login.html" } ),
    #url(r'^registration/logout/$', 'django.contrib.auth.views.logout_then_login' ),
]

src/apps/sociotypetest/urls.py
from django.conf.urls import url

from . import views


app_name = 'sociotypetest'
urlpatterns = [
    url(r'^(?P<personal_id>[0-9]+)/$', views.sociotest, name = 'sociotest'),
    url(r'^(?P<personal_id>[0-9]+)/sociotest_result', views.sociotest_result, name = 'sociotest_result'),
]

src/apps/authentification/models.py
from django.db import models

# Create your models here.

src/apps/personalp/models.py
from datetime import datetime
from django.db import models
#from django.conf import settings
from django.contrib.auth.models import User
from django.conf.global_settings import LANGUAGES
#from django.db.models.signals import post_save
#from django.dispatch import receiver


# Create your models here.
class Personal_info(models.Model):
    user = models.ForeignKey(User, null = True, on_delete=models.CASCADE, related_name='personal_info')
    nick_name = models.CharField(max_length = 100, blank=True)
    description = models.TextField(max_length = 10000, blank=True)
    birth_date = models.DateField(auto_now=False, auto_now_add=False, blank=True,null=True)
    location = models.CharField(max_length=30, blank=True)
    img_pers = models.ImageField(upload_to = 'avatar', blank=True)
    social_type = models.CharField(max_length = 30, blank=True)
    ip_address = models.GenericIPAddressField(unpack_ipv4=True, null=True, verbose_name='IP адрес', blank=True)
    last_activity = models.DateTimeField(verbose_name='Время последней активности', blank=True, null=True)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True)
    language = models.CharField(max_length=7, choices=LANGUAGES, default='ru')
    created_at = models.DateTimeField(auto_now_add=True)

    #def __str__(self):
    #    return str(self.pk) + ".) " + str(self.user.last_name) + " " + self.user.first_name + " " + self.nick_name
    def __str__(self):
        if self.user:
            return str(self.pk) + ".) " + str(self.user.last_name) + " " + self.user.first_name + " " + self.nick_name
        else:
            return str(self.pk)

        # автолинкование профиля пользователя к пользователю при его сохранении
    #def user_post_save(sender, instance, **kwargs):
    #    ( profile, new ) = Personal_info.objects.get_or_create(user=instance)

    #models.signals.post_save.connect(user_post_save, sender=User)
    #class Personal_infoManager(models.Model):
    #    def create_person(self):
    #        new_person = self.create()

    # first_name = models.CharField(max_length = 30)
    # last_name = models.CharField(max_length = 50)
    # email_pers = models.EmailField(default="@mail.ru")

    #@receiver(post_save, sender=User)
    #def create_user_profile(sender, instance, created, **kwargs):
    #    if created:
    #        Personal_info.objects.create(user=instance)

    #@receiver(post_save, sender=User)
    #def save_user_profile(sender, instance, **kwargs):
    #    instance.personal_info.save()

src/apps/sociotypetest/models.py
from django.db import models

class Socionic_type(models.Model):
    symbol = models.CharField(max_length=3, default = '')
    symbol_dif = models.CharField(max_length=4, default = '')
    name = models.CharField(max_length = 50, default = '')
    name_dif = models.CharField(max_length=50, default = '')
    quadra = models.CharField(max_length=15, default = '')
    img_soc = models.ImageField(upload_to = 'sociotypetest/static/img_soc')
    img_description = models.CharField(max_length=200, default = 'none')
    description_short = models.TextField(max_length=5000, default = 'none')
    description = models.TextField(max_length = 10000, default = 'none')
    dichotomies = models.TextField(max_length = 10000, default = 'none')

    def __str__(self):
        return self.symbol + " - " + self.name_dif + " - " + self.name

src/apps/authentification/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from src.apps.personalp.models import Personal_info

class AuthentificationForm(forms.Form):
    username = forms.CharField(label="Username")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

#class AuthentificationForm(AuthenticationForm):
#    form = AuthenticationForm

    #def clean_data(self):
    #    cleaned_data = super(AuthentificationForm, self).clean()
    #    username = cleaned_data.get('username')
    #    password = cleaned_data.get('password')

src/apps/personalp/forms.py
from .models import Personal_info
from django import forms

class PersonalPImg(forms.ModelForm):
    #pers_img = forms.ImageField()
    class Meta:
        model = Personal_info
        fields = ['img_pers']

src/apps/authentification/views.py
from django.shortcuts import render
from django import forms
from django.contrib.auth import authenticate, login
from src.apps.personalp.models import Personal_info
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from src.apps.authentification.forms import AuthentificationForm
from django.contrib.auth import logout
from django.shortcuts import render_to_response
from django.core.exceptions import ValidationError
from django.contrib import messages


#нужна вьюха для формы
def login_for_user(request):
    if request.method == "POST":
        form = AuthentificationForm(request.POST)
        if form.is_valid():
            auth_first_field = request.POST['username']
            auth_second_field = request.POST['password']
            user = authenticate(username=auth_first_field, password=auth_second_field)
            print("request is post")
            if user is not None:
                if user.is_active:
                    login(request, user)
                    pers = Personal_info.objects.get(user=user) #user = username #was an error literal for int()
                    return HttpResponseRedirect(reverse('personalp:personal_info', args=(pers.pk,)))
                else:
                    form = AuthentificationForm(request.POST)
                    messages.error(request, 'Your account is disabled')
                    return render(request, 'auth/auth.html', {'form': form })
                #return HttpResponse("Your account is disabled.")
            else:
                print("User is none")
                form = AuthentificationForm(request.POST)
                messages.error(request, 'Invalid login details supplied.')
                return render(request, 'auth/auth.html', {'form': form })
                # return HttpResponse("Invalid login details supplied.")
        else:
            print("Form is not valid")
            messages.error(request, 'login or password are not correct.')
            return render(request, 'auth/auth.html', {'form':form} )
    else:
        print("No data post")
        return render(request, 'auth/auth.html', {'form' : AuthentificationForm() })


def logout_for_user(request):
    user = None
    logout(request)
    return HttpResponseRedirect(reverse('registration:index'))



#try:
                    #    current_user = Personal_info.objects.get(username=auth_first_field)
                    ##except:
                     #   current_user = Personal_info.objects.get(email=auth_first_field)
                    #finally:
                        #print("Net takogo username or email")
                        #form = AuthentificationForm(request.POST)
                        #return render(request, 'auth/auth.html', {'form': form})
                    #current_user.ip_address = request.META['REMOTE_ADDR']
                    #current_user.last_activity = datetime.now()
                    #current_user.save()

src/apps/personalp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from src.apps.personalp.forms import PersonalPImg
from . models import Personal_info
from django.contrib.auth.decorators import login_required


app_name = 'personalp'

def index(request):
    return render(request, 'main.html')

def personal_info(request, personal_id):
    pers = get_object_or_404(Personal_info, pk=personal_id)
    print('----------------------------------------------')
    print(request.user)
    #print(request.user.get(username = pers.user))
    print('----------------------------------------------')
    if request.method == "POST":
        #Form for uploading avatar photo
        form = PersonalPImg(request.POST, request.FILES)
        if form.is_valid:
            print(form)
            print('---------------------------------')
            print(pers)
            pers.img_pers = form.cleaned_data['img_pers'] #Был косяк, но он прошел
            pers.save()
        return HttpResponseRedirect(reverse('personalp:personal_info', args = (pers.pk,)))
    else:
        form = PersonalPImg()
    return render(request, 'personalp/personal_index.html', {'pers' : pers, 'form' : form} )

src/apps/sociotypetest/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

from src.apps.personalp.models import Personal_info
from .models import Socionic_type
from .forms import sociotype_test

# общий юрл sociotypetest

    # view test result
def sociotest(request, personal_id):
    pers = get_object_or_404(User, pk=personal_id)
    if request.method == 'POST':
        #если форма отправлена и валидна, проитерировать поля формы и записать результат в дихотомии
        form = sociotype_test(request.POST)
        #У нас есть форма и объект персона
        if form.is_valid():
            mbti_type = ''
            dichotomys = {'extraversion': 0, 'introversion': 0, 'sensing': 0, 'intuition': 0, 'thinking': 0,
                      'feeling': 0, 'judging': 0, 'perceiving': 0}
            for num in range(len(form.fields.keys())):
                dichotomys[form.cleaned_data['choice_' + str(num + 1)]] += 1

            mbti_type += 'E' if dichotomys['extraversion'] > dichotomys['introversion'] else  'I'
            mbti_type += 'S' if dichotomys['sensing'] > dichotomys['intuition'] else 'N'
            mbti_type += 'T' if dichotomys['thinking'] > dichotomys['feeling'] else 'F'
            mbti_type += 'J' if dichotomys['judging'] > dichotomys['perceiving'] else 'P'
            pers.social_type = mbti_type
            pers.save()
            #socionic_type = get_object_or_404(Socionic_type, symbol_dif = mbti_type)
            return HttpResponseRedirect(reverse('sociotypetest:sociotest_result', args=(pers.id,)))
            #return render(request, 'sociotypetest/sociotest_result.html',
            #              {'pers': pers, 'dichotomys': dichotomys,
            #               'mbti_type': mbti_type, 'socionic_type': socionic_type}, )
    else:
        form = sociotype_test()
        return render(request, 'sociotypetest/sociotest.html', {'form': form, 'pers' : pers})

def sociotest_result(request, personal_id):
    pers = get_object_or_404(Personal_info, pk = personal_id)
    social_type_all = Socionic_type.objects.all.get()
    if pers.social_type:
        socionic_type = get_object_or_404(Socionic_type, symbol_dif=pers.social_type)
    return render(request, 'sociotypetest/sociotest_result.html', {'pers' : pers, 'socionic_type': socionic_type})

src/templates/footer.html
{% block footer %}
{% load static from staticfiles %}

<div class="clear"></div>
		<div id="footer">
			<div id="footer-innertube">
				<div id="footer-address">
					<h5>Address</h5>
					<ul>
						<li>123 Street Address,</li>
						<li>Lovely City,</li>
						<li>My Country</li>
					</ul>
				</div><!-- footer-address end -->
				<div id="footer-contact">
					<h5>Contact</h5>
					<ul>
						<li>000 123 456 789</li>
						<li><a href="mailto:#" title="Send me an email">address@email.com</a></li>
						<li><a href="contact.php">Contact form<span class="raquo">&#187;</span></a></li>
					</ul>
				</div><!-- footer-contact end -->
				<div id="footer-social">
					<h5>Social</h5>
					<ul>
						<li><a href="#" title=""><img src="{% static 'personalp/static/images/twitter.png'%}" alt="twitter" title="My Twitter profile"></a></li>
						<li><a href="#" title=""><img src="{% static 'personalp/static/images/facebook.png'%}" alt="facebook" title="My Facebook profile"></a></li>
						<li><a href="#" title=""><img src="{% static 'personalp/static/images/flickr.png'%}" alt="flickr" title="My Flickr profile"></a></li>
						<li><a href="#" title=""><img src="{% static 'personalp/static/images/linkedin.png'%}" alt="linkedin" title="My Linkedin profile"></a></li>
					</ul>
				</div><!-- footer-social end -->
				<div id="footer-resume">
					<h5>My resume</h5>
					<div id="download-resume"><a href="#"></a></div>
				</div><!-- footer-resume end -->
				<div class="clear"></div>
				<ul id="footer-nav">
					<li><a href="index.html">Resume</a></li>
					<li><a href="portfolio.html">Portfolio</a></li>
					<li><a href="about.html">About me</a></li>
					<li><a href="contact.php">Contact</a></li>
				</ul>
				<div id="go-top"></div>
				<div class="clear"></div>
			</div><!-- footer-innertube end -->
		</div><!-- footer end -->

{% endblock %}

src/templates/header.html
{% load static from staticfiles %}

 <div id="header">
     <div class="header_logo_site">
        <h1>Соционический клуб</h1>
     </div>
     <ul id="main-nav">
         {% if pers.id != None %}
            <li class="current"><a href="{% url 'personalp:personal_info' pers.id %}">Personal page</a></li>
            <li><a href="{% url 'sociotypetest:sociotest' pers.id %}">Sociotype test</a></li>
            <li><a href="{% url 'sociotypetest:sociotest_result' pers.id %}">About your sociotype</a></li>
         {% endif %}
     </ul>

     <ul>
         {% if pers.id %}
            <li><a href="{% url 'authentification:logout_for_user' %}">Выйти</a></li>
         {% else %}
            <li><a href="{% url 'authentification:login_for_user' %}">Войти</a></li>
            <li><a href="{% url 'registration:register' %}">Регистрация</a></li>
         {% endif %}
     </ul>

     <div class="clear"></div>
 </div>

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load staticfiles %}

    {% block head %}
    {% endblock %}
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css'%}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'personalp/static/css/main.css'%}" />
    <link rel="stylesheet" type="text/css" media="print" href="{% static 'personalp/static/css/print.css'%}"  />
    <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:light' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="{% static 'personalp/static/js/jquery-1.5.2.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'personalp/static/js/jquery.tweet.js'%}"></script>
    <script type="text/javascript" src="{% static 'personalp/static/js/jquery.ScrollTo.js'%}"></script>
    <script type="text/javascript" src="{% static 'personalp/static/js/jquery.prettyPhoto.js'%}"></script>
    <script type="text/javascript" src="{% static 'personalp/static/js/jquery.easing.1.3.js'%}"></script>
    <script type="text/javascript" src="{% static 'personalp/static/js/jquery.quicksand.js'%}"></script>
    <script type="text/javascript" src="{% static 'personalp/static/js/jquery.quicksand-config.js'%}"></script>
    <script type="text/javascript" src="{% static 'personalp/static/js/scripts.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/all.js'%}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta charset="UTF-8">

</head>
    <body>
    <div>
        {% block nav %}
        {% endblock %}
    </div>

    <div class="wrapper">
        <div class="header">
            {% include "header.html" %}
        </div>

        <div class="content">
            {% block content %}
            {% endblock %}
        </div>

        <div class="footer">
            {% include "footer.html" %}
        </div>

    </div>
    </body>
</html>

src/templates/main.html
{% extends "index.html" %}

{% load staticfiles %}

{% block head %}
<title>Main page</title>
{% endblock %}

{% block content %}

<div>Main</div>
<p>Надо написать инфу</p>


{% endblock %}